AllCops:
  TargetRubyVersion: 2.2

  Exclude:
    - db/schema.rb
    - db/migrate/*
    - config/**/*
    - tmp/**/*
    - vendor/bundle/**/*
    - node_modules/**/*
    - bin/*
    - Gemfile
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - config/initializers/simple_form.rb
    - config/initializers/simple_form/*
    - app/services/*
    - spec/models/*
    - app/models/*
    - app/controllers/*
    - app/controllers/users/omniauth_callbacks_controller.rb
